<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useRouter, RouterLink } from 'vue-router'
import { useAuthStore } from '../stores/auth'
const router = useRouter(); const auth = useAuthStore()
const form = reactive({ email: 'admin@taskflow.dev', password: 'password123' }); const errors = reactive<Record<string, string>>({}); const touched = reactive<Record<string, boolean>>({}); const message = ref('')
const isValid = computed(() => form.email.includes('@') && form.password.length >= 6)
function validate() { errors.email = form.email.includes('@') ? '' : 'Enter a valid email'; errors.password = form.password.length >= 6 ? '' : 'Use at least 6 characters'; return !errors.email && !errors.password }
async function onSubmit() { touched.email = touched.password = true; if (!validate()) return; if (!await auth.login(form.email, form.password)) { message.value = 'Invalid email or password.'; return }; router.push('/dashboard') }
</script>
<template><div class="grid min-h-screen place-items-center bg-slate-950 p-5"><div class="grid w-full max-w-5xl overflow-hidden rounded-panel bg-surface shadow-2xl md:grid-cols-2"><section class="hidden bg-primary p-12 text-white md:block"><div class="grid h-10 w-10 place-items-center rounded-xl bg-white/20 text-xl font-bold">T</div><h1 class="mt-20 text-4xl font-bold leading-tight">Bring your work into focus.</h1><p class="mt-5 max-w-sm text-indigo-100">Plan projects, keep momentum and deliver every milestone with your team.</p><div class="mt-16 flex items-center gap-3 text-sm text-indigo-100"><span class="h-2 w-2 rounded-full bg-white" /> One place for your team</div></section><section class="p-8 sm:p-12"><RouterLink to="/login" class="flex items-center gap-2 text-xl font-bold text-ink md:hidden"><span class="grid h-8 w-8 place-items-center rounded-lg bg-primary text-sm text-white">T</span>Taskflow</RouterLink><h2 class="mt-8 text-2xl font-bold">Welcome back</h2><p class="mt-2 text-sm text-secondary">Sign in to your Taskflow workspace.</p><form class="mt-8 space-y-5" @submit.prevent="onSubmit"><label class="block text-sm font-medium">Email<input v-model="form.email" @blur="touched.email = true; validate()" type="email" class="mt-2 w-full rounded-lg border border-border px-3 py-3 outline-none focus:border-primary" /></label><p v-if="touched.email && errors.email" class="-mt-3 text-xs text-danger">{{ errors.email }}</p><label class="block text-sm font-medium">Password<RouterLink to="/forgot-password" class="float-right text-primary">Forgot password?</RouterLink><input v-model="form.password" @blur="touched.password = true; validate()" type="password" class="mt-2 w-full rounded-lg border border-border px-3 py-3 outline-none focus:border-primary" /></label><p v-if="touched.password && errors.password" class="-mt-3 text-xs text-danger">{{ errors.password }}</p><p v-if="message" class="rounded-lg bg-danger/10 p-3 text-sm text-danger">{{ message }}</p><button :disabled="!isValid" class="w-full rounded-lg bg-primary py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">Sign in</button></form><p class="mt-6 text-center text-sm text-secondary">New to Taskflow? <RouterLink to="/signup" class="font-semibold text-primary">Create an account</RouterLink></p></section></div></div></template>
