<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import EmptyState from '../components/EmptyState.vue'
import LoadingState from '../components/LoadingState.vue'
import { useProjectStore } from '../stores/projects'
import type { Project } from '../types'
const router = useRouter(); const store = useProjectStore(); const projects = ref<Project[]>([]); const loading = ref(true); const query = ref(''); const status = ref('All')
onMounted(async () => { projects.value = await store.getAll(); loading.value = false })
const filtered = computed(() => projects.value.filter((project) => (status.value === 'All' || project.status === status.value) && project.title.toLowerCase().includes(query.value.toLowerCase())))
</script><template><div><div class="flex flex-wrap items-center justify-between gap-4"><div><h1 class="text-3xl font-bold">Projects</h1><p class="mt-2 text-sm text-secondary">Everything your team is actively shipping.</p></div><button @click="router.push('/projects/new')" class="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white">+ New project</button></div><div class="mt-7 flex flex-wrap gap-3"><input v-model="query" placeholder="Search projects..." class="w-full rounded-lg border border-border bg-surface px-3 py-2.5 text-sm sm:w-72" /><select v-model="status" class="rounded-lg border border-border bg-surface px-3 py-2.5 text-sm"><option>All</option><option>Active</option><option>Planning</option><option>Complete</option></select></div><LoadingState v-if="loading" class="mt-7" label="Loading projects" :rows="3" /><EmptyState v-else-if="!filtered.length" class="mt-10" title="No projects found" description="Try changing your filters, or create a project to begin." action-label="Create a project" @action="router.push('/projects/new')" /><div v-else class="mt-7 grid gap-5 md:grid-cols-2 xl:grid-cols-3"><button v-for="project in filtered" :key="project.id" @click="router.push(`/projects/${project.id}`)" class="rounded-panel border border-border bg-surface p-5 text-left transition hover:-translate-y-1 hover:shadow-lg"><div class="flex justify-between"><span :class="project.color" class="h-10 w-10 rounded-xl" /><span class="rounded-full bg-surface-muted px-2.5 py-1 text-xs font-semibold text-secondary">{{ project.status }}</span></div><h2 class="mt-5 font-bold">{{ project.title }}</h2><p class="mt-2 h-10 text-sm text-secondary">{{ project.description }}</p><div class="mt-5 flex justify-between text-xs"><span class="font-semibold">Progress</span><span>{{ project.progress }}%</span></div><div class="mt-2 h-2 rounded-full bg-surface-muted"><div :class="project.color" class="h-full rounded-full" :style="{ width: `${project.progress}%` }" /></div><p class="mt-5 text-xs text-muted">Due {{ project.dueDate }}</p></button></div></div></template>
