<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useRouter } from 'vue-router'
import { useProjectStore } from '../stores/projects'
import type { ProjectStatus } from '../types'
const router = useRouter(); const store = useProjectStore(); const form = reactive({ title: '', description: '', status: 'Planning' as ProjectStatus, dueDate: '', color: 'bg-violet-500' }); const errors = reactive<Record<string,string>>({}); const touched = reactive<Record<string,boolean>>({}); const success = ref(''); const isValid = computed(() => form.title.trim().length >= 3 && form.description.trim().length >= 10 && form.dueDate)
function validate() { errors.title = form.title.trim().length >= 3 ? '' : 'Use at least 3 characters'; errors.description = form.description.trim().length >= 10 ? '' : 'Add at least 10 characters'; errors.dueDate = form.dueDate ? '' : 'Choose a due date'; return !Object.values(errors).some(Boolean) }
async function onSubmit() { Object.assign(touched, { title: true, description: true, dueDate: true }); if (!validate()) return; const project = await store.create({ ...form, dueDate: new Date(form.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }), members: ['u1'] }); success.value = 'Project created successfully.'; setTimeout(() => router.push(`/projects/${project.id}`), 500) }
</script><template><div class="mx-auto max-w-2xl"><button @click="router.back()" class="text-sm font-semibold text-primary">← Back to projects</button><h1 class="mt-5 text-3xl font-bold">Create a project</h1><p class="mt-2 text-sm text-secondary">Give your team a shared home for the work ahead.</p><form class="mt-8 rounded-panel border border-border bg-surface p-6 sm:p-8" @submit.prevent="onSubmit"><div class="space-y-5"><label class="block text-sm font-medium">Project name<input v-model="form.title" @blur="touched.title = true; validate()" placeholder="e.g. Summer product launch" class="mt-2 w-full rounded-lg border border-border px-3 py-3" /></label><p v-if="touched.title && errors.title" class="text-xs text-danger">{{ errors.title }}</p><label class="block text-sm font-medium">Description<textarea v-model="form.description" @blur="touched.description = true; validate()" rows="4" class="mt-2 w-full rounded-lg border border-border px-3 py-3" /></label><p v-if="touched.description && errors.description" class="text-xs text-danger">{{ errors.description }}</p><div class="grid gap-5 sm:grid-cols-2"><label class="text-sm font-medium">Status<select v-model="form.status" class="mt-2 w-full rounded-lg border border-border px-3 py-3"><option>Planning</option><option>Active</option></select></label><label class="text-sm font-medium">Target date<input v-model="form.dueDate" @blur="touched.dueDate = true; validate()" type="date" class="mt-2 w-full rounded-lg border border-border px-3 py-3" /></label></div><p v-if="touched.dueDate && errors.dueDate" class="text-xs text-danger">{{ errors.dueDate }}</p></div><p v-if="success" class="mt-5 rounded-lg bg-success/10 p-3 text-sm text-success">{{ success }}</p><div class="mt-8 flex justify-end gap-3"><button type="button" @click="router.back()" class="rounded-lg border border-border px-4 py-2.5 text-sm font-semibold">Cancel</button><button :disabled="!isValid" class="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Create project</button></div></form></div></template>
