<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { RouterLink, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth'
const router = useRouter(); const auth = useAuthStore(); const form = reactive({ name: '', email: '', password: '' }); const errors = reactive<Record<string,string>>({}); const touched = reactive<Record<string,boolean>>({}); const message = ref(''); const isValid = computed(() => form.name.trim().length > 1 && form.email.includes('@') && form.password.length >= 6)
function validate() { errors.name = form.name.trim().length > 1 ? '' : 'Enter your name'; errors.email = form.email.includes('@') ? '' : 'Enter a valid email'; errors.password = form.password.length >= 6 ? '' : 'Use at least 6 characters'; return !Object.values(errors).some(Boolean) }
async function onSubmit() { Object.assign(touched, { name: true, email: true, password: true }); if (!validate()) return; if (!await auth.signup(form.name, form.email, form.password)) { message.value = 'This email is already in use.'; return }; router.push('/dashboard') }
</script>
<template><div class="grid min-h-screen place-items-center bg-primary-soft p-5"><div class="w-full max-w-md rounded-panel bg-surface p-8 shadow-xl sm:p-10"><RouterLink to="/login" class="flex items-center gap-2 text-xl font-bold"><span class="grid h-9 w-9 place-items-center rounded-xl bg-primary text-white">T</span>Taskflow</RouterLink><h1 class="mt-8 text-2xl font-bold">Start collaborating</h1><p class="mt-2 text-sm text-secondary">Create your workspace account in a minute.</p><form class="mt-7 space-y-4" @submit.prevent="onSubmit"><label class="block text-sm font-medium">Full name<input v-model="form.name" @blur="touched.name = true; validate()" class="mt-1.5 w-full rounded-lg border border-border px-3 py-2.5" /></label><p v-if="touched.name && errors.name" class="text-xs text-danger">{{ errors.name }}</p><label class="block text-sm font-medium">Work email<input v-model="form.email" @blur="touched.email = true; validate()" type="email" class="mt-1.5 w-full rounded-lg border border-border px-3 py-2.5" /></label><p v-if="touched.email && errors.email" class="text-xs text-danger">{{ errors.email }}</p><label class="block text-sm font-medium">Password<input v-model="form.password" @blur="touched.password = true; validate()" type="password" class="mt-1.5 w-full rounded-lg border border-border px-3 py-2.5" /></label><p v-if="touched.password && errors.password" class="text-xs text-danger">{{ errors.password }}</p><p v-if="message" class="rounded-lg bg-danger/10 p-3 text-sm text-danger">{{ message }}</p><button :disabled="!isValid" class="w-full rounded-lg bg-primary py-3 font-semibold text-white disabled:opacity-50">Create account</button></form><p class="mt-5 text-center text-sm text-secondary">Already have an account? <RouterLink to="/login" class="font-semibold text-primary">Sign in</RouterLink></p></div></div></template>
