<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useProjectStore } from '../stores/projects'
import { useTaskStore } from '../stores/tasks'
import { demoUsers } from '../data/mockData'
import type { Project, TaskStatus, Priority } from '../types'
const route = useRoute(); const router = useRouter(); const taskStore = useTaskStore(); const projectStore = useProjectStore(); const projects = ref<Project[]>([]); const form = reactive({ title: '', description: '', projectId: String(route.params.projectId ?? ''), status: 'To do' as TaskStatus, priority: 'Medium' as Priority, assigneeId: 'u1', dueDate: '' }); const errors = reactive<Record<string,string>>({}); const success = ref(''); const isValid = computed(() => form.title.trim().length >= 3 && form.projectId && form.dueDate)
onMounted(async () => { projects.value = await projectStore.getAll() })
function validate() { errors.title = form.title.trim().length >= 3 ? '' : 'Add a task title'; errors.projectId = form.projectId ? '' : 'Choose a project'; errors.dueDate = form.dueDate ? '' : 'Choose a due date'; return !Object.values(errors).some(Boolean) }
async function onSubmit() { if (!validate()) return; const task = await taskStore.create(form); success.value = 'Task created successfully.'; setTimeout(() => router.push(`/tasks/${task.id}`), 450) }
</script><template><div class="mx-auto max-w-2xl"><button @click="router.back()" class="text-sm font-semibold text-primary">← Back</button><h1 class="mt-5 text-3xl font-bold">Create a task</h1><form class="mt-7 rounded-panel border border-border bg-surface p-6 sm:p-8" @submit.prevent="onSubmit"><div class="space-y-5"><label class="block text-sm font-medium">Task title<input v-model="form.title" @blur="validate" class="mt-2 w-full rounded-lg border border-border px-3 py-3" /></label><p v-if="errors.title" class="text-xs text-danger">{{ errors.title }}</p><label class="block text-sm font-medium">Description<textarea v-model="form.description" rows="3" class="mt-2 w-full rounded-lg border border-border px-3 py-3" /></label><div class="grid gap-5 sm:grid-cols-2"><label class="text-sm font-medium">Project<select v-model="form.projectId" @change="validate" class="mt-2 w-full rounded-lg border border-border px-3 py-3"><option value="">Select a project</option><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.title }}</option></select></label><label class="text-sm font-medium">Assignee<select v-model="form.assigneeId" class="mt-2 w-full rounded-lg border border-border px-3 py-3"><option v-for="user in demoUsers" :key="user.id" :value="user.id">{{ user.name }}</option></select></label><label class="text-sm font-medium">Status<select v-model="form.status" class="mt-2 w-full rounded-lg border border-border px-3 py-3"><option>To do</option><option>In progress</option><option>Done</option></select></label><label class="text-sm font-medium">Priority<select v-model="form.priority" class="mt-2 w-full rounded-lg border border-border px-3 py-3"><option>High</option><option>Medium</option><option>Low</option></select></label></div><label class="block text-sm font-medium">Due date<input v-model="form.dueDate" @blur="validate" type="date" class="mt-2 w-full rounded-lg border border-border px-3 py-3" /></label><p v-if="errors.projectId || errors.dueDate" class="text-xs text-danger">{{ errors.projectId || errors.dueDate }}</p></div><p v-if="success" class="mt-5 rounded-lg bg-success/10 p-3 text-sm text-success">{{ success }}</p><div class="mt-8 flex justify-end gap-3"><button type="button" @click="router.back()" class="rounded-lg border border-border px-4 py-2.5 text-sm font-semibold">Cancel</button><button :disabled="!isValid" class="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">Create task</button></div></form></div></template>
