<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import EmptyState from '../components/EmptyState.vue'
import LoadingState from '../components/LoadingState.vue'
import { useTaskStore } from '../stores/tasks'
import { demoUsers } from '../data/mockData'
import type { Task } from '../types'
const router = useRouter(); const store = useTaskStore(); const tasks = ref<Task[]>([]); const loading = ref(true); const status = ref('All'); const priority = ref('All'); const query = ref('')
onMounted(async () => { tasks.value = await store.getAll(); loading.value = false })
const filtered = computed(() => tasks.value.filter((task) => (status.value === 'All' || task.status === status.value) && (priority.value === 'All' || task.priority === priority.value) && task.title.toLowerCase().includes(query.value.toLowerCase())))
</script><template><div><div class="flex justify-between"><div><h1 class="text-3xl font-bold">My tasks</h1><p class="mt-2 text-sm text-secondary">Stay focused on the work that needs you.</p></div><button @click="router.push('/tasks/new')" class="rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white">+ Add task</button></div><div class="mt-7 flex flex-wrap gap-3"><input v-model="query" placeholder="Search tasks..." class="rounded-lg border border-border bg-surface px-3 py-2.5 text-sm" /><select v-model="status" class="rounded-lg border border-border bg-surface px-3 py-2.5 text-sm"><option>All</option><option>To do</option><option>In progress</option><option>Done</option></select><select v-model="priority" class="rounded-lg border border-border bg-surface px-3 py-2.5 text-sm"><option>All</option><option>High</option><option>Medium</option><option>Low</option></select></div><LoadingState v-if="loading" class="mt-6" label="Loading tasks" :rows="4" /><EmptyState v-else-if="!filtered.length" class="mt-7" title="No tasks found" description="Try changing your filters or add a task to get started." action-label="Add task" @action="router.push('/tasks/new')" /><div v-else class="mt-6 overflow-hidden rounded-panel border border-border bg-surface"><button v-for="task in filtered" :key="task.id" @click="router.push(`/tasks/${task.id}`)" class="flex w-full items-center justify-between gap-4 border-b border-border p-4 text-left last:border-0 hover:bg-surface-muted"><div><p class="font-semibold">{{ task.title }}</p><p class="mt-1 text-xs text-secondary">{{ demoUsers.find(user => user.id === task.assigneeId)?.name }} · Due {{ task.dueDate }}</p></div><div class="flex gap-2"><span class="rounded-full bg-primary-soft px-2 py-1 text-xs font-semibold text-primary">{{ task.status }}</span><span class="rounded-full bg-surface-muted px-2 py-1 text-xs font-semibold">{{ task.priority }}</span></div></button></div></div></template>
