<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useTaskStore } from '../stores/tasks'
import { useProjectStore } from '../stores/projects'
import { demoUsers } from '../data/mockData'
import type { Task } from '../types'
const route = useRoute(); const router = useRouter(); const task = ref<Task>(); const projectTitle = ref(''); const loading = ref(true); const confirmDelete = ref(false); const store = useTaskStore(); const projects = useProjectStore()
onMounted(async () => { task.value = await store.getById(String(route.params.id)); if (task.value) projectTitle.value = (await projects.getById(task.value.projectId))?.title ?? 'Project'; loading.value = false })
async function updateStatus() { if (task.value) task.value = await store.update(task.value.id, { status: task.value.status }) }
async function remove() { if (!task.value) return; const projectId = task.value.projectId; await store.remove(task.value.id); router.push(`/projects/${projectId}`) }
</script><template><div v-if="loading" class="h-72 animate-pulse rounded-panel bg-slate-200" /><div v-else-if="!task" class="text-center"><h1 class="text-xl font-bold">Task not found</h1><button @click="router.push('/tasks')" class="mt-4 text-primary">Back to tasks</button></div><div v-else class="mx-auto max-w-3xl"><button @click="router.push(`/projects/${task.projectId}`)" class="text-sm font-semibold text-primary">← {{ projectTitle }}</button><div class="mt-6 rounded-panel border border-border bg-surface p-6 sm:p-8"><div class="flex items-start justify-between gap-5"><div><span class="rounded-full bg-surface-muted px-2 py-1 text-xs font-semibold">{{ task.priority }} priority</span><h1 class="mt-4 text-3xl font-bold">{{ task.title }}</h1></div><button @click="confirmDelete = true" class="rounded-lg border border-danger px-3 py-2 text-sm font-semibold text-danger">Delete</button></div><p class="mt-5 text-secondary">{{ task.description || 'No description provided.' }}</p><div class="mt-7 grid gap-5 border-t border-border pt-6 sm:grid-cols-2"><label class="text-sm font-medium">Status<select v-model="task.status" @change="updateStatus" class="mt-2 w-full rounded-lg border border-border px-3 py-2.5"><option>To do</option><option>In progress</option><option>Done</option></select></label><div><p class="text-sm font-medium">Assignee</p><p class="mt-2 text-sm text-secondary">{{ demoUsers.find(user => user.id === task.assigneeId)?.name }}</p></div></div></div><div v-if="confirmDelete" class="fixed inset-0 z-20 grid place-items-center bg-slate-950/50 p-5"><div class="w-full max-w-sm rounded-panel bg-surface p-6 shadow-xl"><h2 class="text-lg font-bold">Delete this task?</h2><p class="mt-2 text-sm text-secondary">This can’t be undone.</p><div class="mt-6 flex justify-end gap-3"><button @click="confirmDelete = false" class="rounded-lg border border-border px-4 py-2 text-sm font-semibold">Keep task</button><button @click="remove" class="rounded-lg bg-danger px-4 py-2 text-sm font-semibold text-white">Delete task</button></div></div></div></div></template>
